import type { SeedQuestion } from "./types";

// Original Math items authored for XeduSAT. ~25% Student-Produced Response
// (SPR), ordered roughly easy → hard, covering every Math domain/skill.
export const mathQuestions: SeedQuestion[] = [
  // ---- Algebra ----
  {
    section: "MATH",
    domain: "Algebra",
    skill: "Linear Equations",
    difficulty: "easy",
    type: "MCQ",
    stem: "If 5x − 3 = 2x + 12, what is the value of x?",
    choices: ["3", "5", "9", "15"],
    correctAnswer: "B",
    explanation: "Subtract 2x: 3x − 3 = 12. Add 3: 3x = 15, so x = 5.",
  },
  {
    section: "MATH",
    domain: "Algebra",
    skill: "Linear Functions",
    difficulty: "easy",
    type: "MCQ",
    stem: "A line passes through the points (0, 4) and (2, 10). What is the slope of the line?",
    choices: ["2", "3", "4", "6"],
    correctAnswer: "B",
    explanation: "Slope = (10 − 4) / (2 − 0) = 6 / 2 = 3.",
  },
  {
    section: "MATH",
    domain: "Algebra",
    skill: "Linear Inequalities",
    difficulty: "medium",
    type: "MCQ",
    stem: "A food truck must sell at least 40 meals to break even. It has already sold 18 meals. If m is the number of additional meals needed to break even, which inequality represents this situation?",
    choices: ["m ≥ 22", "m ≤ 22", "m ≥ 58", "m > 40"],
    correctAnswer: "A",
    explanation: "The truck needs 18 + m ≥ 40, so m ≥ 22 additional meals.",
  },
  {
    section: "MATH",
    domain: "Algebra",
    skill: "Systems of Linear Equations",
    difficulty: "medium",
    type: "SPR",
    stem: "A store sells notebooks for $3 each and pens for $1 each. Maria buys 10 items in total and spends $22. How many notebooks did she buy?",
    correctAnswer: "6",
    explanation:
      "Let n = notebooks, p = pens. n + p = 10 and 3n + p = 22. Subtracting: 2n = 12, so n = 6.",
  },
  {
    section: "MATH",
    domain: "Algebra",
    skill: "Systems of Linear Equations",
    difficulty: "hard",
    type: "MCQ",
    stem: "For which value of c does the system 2x + 3y = 8 and 4x + 6y = c have infinitely many solutions?",
    choices: ["16", "8", "4", "12"],
    correctAnswer: "A",
    explanation:
      "The second equation must be a multiple of the first. Multiplying 2x + 3y = 8 by 2 gives 4x + 6y = 16, so c = 16.",
  },
  {
    section: "MATH",
    domain: "Algebra",
    skill: "Linear Equations",
    difficulty: "hard",
    type: "MCQ",
    stem: "In the equation ax + 12 = 3x + b, a and b are constants. If the equation has no solution, which statement must be true?",
    choices: [
      "a = 3 and b ≠ 12",
      "a = 3 and b = 12",
      "a ≠ 3 and b = 12",
      "a ≠ 3 and b ≠ 12",
    ],
    correctAnswer: "A",
    explanation:
      "No solution requires equal coefficients of x but unequal constants: a = 3 (so the x-terms cancel) and b ≠ 12 (so the constants conflict).",
  },
  // ---- Advanced Math ----
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Quadratics",
    difficulty: "medium",
    type: "MCQ",
    stem: "What are the solutions to the equation x² − 5x + 6 = 0?",
    choices: ["x = 2 and x = 3", "x = −2 and x = −3", "x = 1 and x = 6", "x = −1 and x = 6"],
    correctAnswer: "A",
    explanation: "Factor: (x − 2)(x − 3) = 0, so x = 2 or x = 3.",
  },
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Quadratics",
    difficulty: "medium",
    type: "SPR",
    stem: "The quadratic function f(x) = x² − 8x + 15 has its minimum value at x = h. What is the value of h?",
    correctAnswer: "4",
    explanation:
      "The vertex x-coordinate is h = −b/(2a) = 8/2 = 4.",
  },
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Polynomials and Rational Expressions",
    difficulty: "medium",
    type: "MCQ",
    stem: "If (x − 4) is a factor of the polynomial p(x) = x² + kx − 12, what is the value of k?",
    choices: ["−1", "1", "3", "−3"],
    correctAnswer: "A",
    explanation:
      "Since (x − 4) is a factor, p(4) = 0: 16 + 4k − 12 = 0 → 4k = −4 → k = −1.",
  },
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Radicals and Absolute Value",
    difficulty: "medium",
    type: "MCQ",
    stem: "What is the solution to the equation √(2x + 1) = 5?",
    choices: ["12", "13", "24", "2"],
    correctAnswer: "A",
    explanation: "Square both sides: 2x + 1 = 25 → 2x = 24 → x = 12.",
  },
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Exponentials",
    difficulty: "hard",
    type: "MCQ",
    stem: "A sample of a radioactive substance has a mass of 80 grams and loses half its mass every 6 years. Which function gives the mass, in grams, remaining after t years?",
    choices: [
      "m(t) = 80 · (1/2)^(t/6)",
      "m(t) = 80 · (1/2)^(6t)",
      "m(t) = 80 · (1/2)^(t) · 6",
      "m(t) = 80 − 6t",
    ],
    correctAnswer: "A",
    explanation:
      "Halving every 6 years means the number of half-lives after t years is t/6, giving 80 · (1/2)^(t/6).",
  },
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Function Notation and Transformations",
    difficulty: "hard",
    type: "MCQ",
    stem: "The function g is defined by g(x) = 2·f(x) − 1. If f(3) = 4, what is the value of g(3)?",
    choices: ["7", "8", "9", "3"],
    correctAnswer: "A",
    explanation: "g(3) = 2·f(3) − 1 = 2·4 − 1 = 7.",
  },
  {
    section: "MATH",
    domain: "Advanced Math",
    skill: "Nonlinear Systems",
    difficulty: "hard",
    type: "MCQ",
    stem: "The graphs of y = x² and y = x + 6 intersect at two points. What is the sum of the y-coordinates of these two points?",
    choices: ["13", "6", "9", "5"],
    correctAnswer: "A",
    explanation:
      "x² = x + 6 → x² − x − 6 = 0 → (x − 3)(x + 2) = 0, so x = 3 or x = −2. The y-values are 9 and 4, summing to 13.",
  },
  // ---- Problem-Solving and Data Analysis ----
  {
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Ratios and Rates",
    difficulty: "easy",
    type: "MCQ",
    stem: "A car travels 150 miles in 3 hours at a constant speed. At this rate, how far will it travel in 5 hours?",
    choices: ["250 miles", "200 miles", "300 miles", "450 miles"],
    correctAnswer: "A",
    explanation: "Speed = 150/3 = 50 mph. In 5 hours: 50 × 5 = 250 miles.",
  },
  {
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Percentages",
    difficulty: "medium",
    type: "MCQ",
    stem: "A population of a town increased from 8,000 to 9,200 over one year. What was the percent increase?",
    choices: ["15%", "12%", "13%", "20%"],
    correctAnswer: "A",
    explanation: "Increase = 1,200. Percent = 1,200 / 8,000 = 0.15 = 15%.",
  },
  {
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Statistics",
    difficulty: "medium",
    type: "SPR",
    stem: "The list of values 4, 7, 7, 9, 13 represents daily sales. What is the median of the data set?",
    correctAnswer: "7",
    explanation: "Ordered, the middle (third) of five values is 7.",
  },
  {
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Two-Way Tables",
    difficulty: "medium",
    type: "MCQ",
    graphSpec: {
      type: "table",
      title: "Students by grade and lunch choice",
      headers: ["", "Hot lunch", "Cold lunch", "Total"],
      rows: [
        ["Grade 9", 30, 20, 50],
        ["Grade 10", 25, 25, 50],
        ["Total", 55, 45, 100],
      ],
    },
    stem: "Based on the table, if one of the 100 students is chosen at random, what is the probability that the student is in Grade 9 and chose hot lunch?",
    choices: ["0.30", "0.55", "0.50", "0.60"],
    correctAnswer: "A",
    explanation: "30 students are Grade 9 with hot lunch, out of 100: 30/100 = 0.30.",
  },
  {
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Scatterplots and Line of Best Fit",
    difficulty: "hard",
    type: "MCQ",
    stem: "A line of best fit for a data set relating hours studied (x) to test score (y) is ŷ = 6x + 52. Based on this model, how many points does the score increase for each additional hour studied?",
    choices: ["6", "52", "58", "46"],
    correctAnswer: "A",
    explanation: "The slope, 6, is the predicted increase in score per additional hour studied.",
  },
  // ---- Geometry and Trigonometry ----
  {
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Area and Volume",
    difficulty: "easy",
    type: "MCQ",
    stem: "A rectangular prism has length 5, width 3, and height 4. What is its volume?",
    choices: ["60", "12", "47", "35"],
    correctAnswer: "A",
    explanation: "Volume = length × width × height = 5 × 3 × 4 = 60.",
  },
  {
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Triangles",
    difficulty: "medium",
    type: "SPR",
    stem: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?",
    correctAnswer: "10",
    explanation: "By the Pythagorean theorem: √(6² + 8²) = √(36 + 64) = √100 = 10.",
  },
  {
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Right-Triangle Trigonometry",
    difficulty: "hard",
    type: "MCQ",
    stem: "In a right triangle, one acute angle θ satisfies sin θ = 3/5. What is the value of cos θ?",
    choices: ["4/5", "3/4", "5/4", "5/3"],
    correctAnswer: "A",
    explanation:
      "A 3-4-5 right triangle: if sin θ = 3/5 (opposite/hypotenuse), the adjacent leg is 4, so cos θ = 4/5.",
  },
  {
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Circles",
    difficulty: "hard",
    type: "MCQ",
    stem: "A circle in the xy-plane has the equation (x − 2)² + (y + 3)² = 16. What are the coordinates of its center and the length of its radius?",
    choices: [
      "Center (2, −3), radius 4",
      "Center (−2, 3), radius 4",
      "Center (2, −3), radius 16",
      "Center (−2, 3), radius 16",
    ],
    correctAnswer: "A",
    explanation:
      "In (x − h)² + (y − k)² = r², the center is (h, k) = (2, −3) and r = √16 = 4.",
  },
];
